-- Workspaces (folders) for panoramas + sharing via workspace_access
--
-- Run in Supabase Dashboard -> SQL Editor.
-- Safe to run multiple times.

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, name)
);

create index if not exists idx_workspaces_user_id on public.workspaces(user_id);
create index if not exists idx_workspaces_org_id on public.workspaces(org_id);
create index if not exists idx_workspaces_updated_at on public.workspaces(updated_at desc);

create table if not exists public.workspace_access (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_type text not null check (access_type in ('client', 'viewer')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  unique (workspace_id, user_id)
);

create index if not exists idx_workspace_access_workspace_id on public.workspace_access(workspace_id);
create index if not exists idx_workspace_access_user_id on public.workspace_access(user_id);

alter table public.panoramas
  add column if not exists workspace_id uuid references public.workspaces(id) on delete set null;

create index if not exists idx_panoramas_workspace_id on public.panoramas(workspace_id);

