-- ============================================================
-- PropMark - Supabase schema (run in SQL Editor)
-- ============================================================
-- Run this in Supabase Dashboard → SQL Editor → New query

-- 1) Profiles: app users with role (admin | user)
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('admin', 'user')),
  display_name text,
  email text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_profiles_user_id on public.profiles(user_id);

-- 2) Panoramas (owner = user_id)
create table if not exists public.panoramas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  filename text not null,
  original_filename text not null,
  width int default 0,
  height int default 0,
  is_360 boolean default false,
  image_data text default null,
  image_content_type text default 'image/jpeg',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_panoramas_user_id on public.panoramas(user_id);
create index if not exists idx_panoramas_updated_at on public.panoramas(updated_at desc);

-- 3) Plots
create table if not exists public.plots (
  id bigint generated by default as identity primary key,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  -- Optional: link a plot to another panorama for "Enter Panorama" navigation
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  name text not null,
  area text default '',
  price text default '',
  status text default 'available',
  description text default '',
  color text default 'emerald',
  media_photo text default '',
  media_video text default '',
  image_data text default null,
  image_filename text default null,
  image_content_type text default 'image/jpeg',
  points jsonb not null default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_plots_panorama_id on public.plots(panorama_id);

-- 4) 360 marker points (stored as HTML markers metadata)
create table if not exists public.plot_markers (
  id uuid primary key default gen_random_uuid(),
  plot_id text not null,
  name text not null,
  description text default '',
  status text default 'available' check (status in ('available', 'reserved', 'on_hold', 'sold')),
  marker_style text default 'glass',
  marker_icon text default 'mdi:map-marker-radius',
  marker_color text default '#4ade80',
  image_base64 text default null,
  image_filename text default null,
  -- Optional: link a hotspot marker to another panorama
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  longitude double precision not null,
  latitude double precision not null,
  created_at timestamptz default now()
);

create index if not exists idx_plot_markers_plot_id on public.plot_markers(plot_id);
create index if not exists idx_plot_markers_created_at on public.plot_markers(created_at desc);

-- 5) Panorama access: admin/owner grants client or viewer access to a user
create table if not exists public.panorama_access (
  id bigint generated by default as identity primary key,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_type text not null check (access_type in ('client', 'viewer')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  unique(panorama_id, user_id)
);

create index if not exists idx_panorama_access_panorama_id on public.panorama_access(panorama_id);
create index if not exists idx_panorama_access_user_id on public.panorama_access(user_id);

-- 6) Trigger: create profile with role 'user' when a new auth user is created
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 7) Grant first admin: run after creating your first user, set their profile to admin
-- update public.profiles set role = 'admin' where user_id = 'YOUR-AUTH-USER-UUID';
