-- ============================================================
-- Markers: point markers on panoramas (admin adds; clients can edit details only)
-- Run in Supabase Dashboard → SQL Editor
-- ============================================================

create table if not exists public.markers (
  id bigint generated by default as identity primary key,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  marker_type text not null default 'pin' check (marker_type in ('pin', 'flag', 'star', 'info', 'heart', 'warning', 'check')),
  name text not null default '',
  description text default '',
  position jsonb not null default '{"x": 0, "y": 0}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_markers_panorama_id on public.markers(panorama_id);

comment on table public.markers is 'Point markers on panorama (2D x,y or 3D derived). Only owner/admin add; clients can edit name/description only.';
