-- ============================================================
-- Project Plans – migration
-- Bundles multiple building maps into a single shareable view
-- ============================================================

-- 1) Project Plans
create table if not exists public.project_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null default 'Project Plan',
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_project_plans_user on public.project_plans(user_id);
create index if not exists idx_project_plans_share_token on public.project_plans(share_token);

-- 2) Project Plan ↔ Building Maps (many-to-many link table)
create table if not exists public.project_plan_maps (
  id bigint generated by default as identity primary key,
  project_plan_id uuid not null references public.project_plans(id) on delete cascade,
  building_map_id uuid not null references public.building_maps(id) on delete cascade,
  sort_order int not null default 0,
  created_at timestamptz default now(),
  unique(project_plan_id, building_map_id)
);

create index if not exists idx_project_plan_maps_plan on public.project_plan_maps(project_plan_id);
create index if not exists idx_project_plan_maps_building on public.project_plan_maps(building_map_id);
