DROP INDEX IF EXISTS public.idx_panoramas_is_published;
DROP INDEX IF EXISTS public.idx_panoramas_location_city;
DROP INDEX IF EXISTS public.idx_panoramas_project_type;
DROP INDEX IF EXISTS public.idx_panoramas_launch_date;
DROP INDEX IF EXISTS public.idx_panoramas_builder_name;

ALTER TABLE public.panoramas DROP COLUMN IF EXISTS location_address;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS location_city;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS location_state;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS location_lat;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS location_lng;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS google_maps_link;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS rera_registration;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS launch_date;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS possession_date;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS builder_name;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS project_type;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS total_area;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS description;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS amenities;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS is_published;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS brochure_url;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS contact_phone;
ALTER TABLE public.panoramas DROP COLUMN IF EXISTS contact_email;

ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS location_address text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS location_city text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS location_state text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS location_lat double precision;
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS location_lng double precision;
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS google_maps_link text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS rera_registration text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS launch_date date;
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS possession_date text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS builder_name text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS project_type text default 'residential';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS total_area text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS description text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS amenities jsonb default '[]';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS is_published boolean default false;
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS brochure_url text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS contact_phone text default '';
ALTER TABLE public.workspaces ADD COLUMN IF NOT EXISTS contact_email text default '';

CREATE INDEX IF NOT EXISTS idx_workspaces_is_published ON public.workspaces(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_workspaces_location_city ON public.workspaces(location_city);
CREATE INDEX IF NOT EXISTS idx_workspaces_project_type ON public.workspaces(project_type);
CREATE INDEX IF NOT EXISTS idx_workspaces_launch_date ON public.workspaces(launch_date DESC);
CREATE INDEX IF NOT EXISTS idx_workspaces_builder_name ON public.workspaces(builder_name);
