create table if not exists public.mobile_panoramas (
  id bigint generated by default as identity (start with 1000000000) primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  panorama_parent_id bigint not null references public.panoramas(id) on delete cascade,
  name text not null,
  filename text not null,
  original_filename text not null,
  width int default 0,
  height int default 0,
  is_360 boolean default false,
  use_animated_icons boolean default false,
  start_view jsonb default null,
  image_data text default null,
  image_content_type text default 'image/jpeg',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (panorama_parent_id)
);

create index if not exists idx_mobile_panoramas_user_id on public.mobile_panoramas(user_id);
create index if not exists idx_mobile_panoramas_org_id on public.mobile_panoramas(org_id);
create index if not exists idx_mobile_panoramas_workspace_id on public.mobile_panoramas(workspace_id);
create index if not exists idx_mobile_panoramas_parent_id on public.mobile_panoramas(panorama_parent_id);
