-- ============================================================
-- Building Maps + Building Zones – migration
-- ============================================================

-- 1) Building maps (building panorama/photo containers)
create table if not exists public.building_maps (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  catalogue_id uuid references public.floor_plan_catalogues(id) on delete set null,
  name text not null default 'Building Map',
  image_filename text not null,
  image_width int default 0,
  image_height int default 0,
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_building_maps_user on public.building_maps(user_id);
create index if not exists idx_building_maps_workspace on public.building_maps(workspace_id);
create index if not exists idx_building_maps_catalogue on public.building_maps(catalogue_id);
create index if not exists idx_building_maps_share_token on public.building_maps(share_token);

-- 2) Building zones (polygon areas drawn on a building map)
create table if not exists public.building_zones (
  id bigint generated by default as identity primary key,
  building_map_id uuid not null references public.building_maps(id) on delete cascade,
  name text not null,
  floor_number int not null default 0 check (floor_number >= 0 and floor_number <= 100),
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  linked_floor_plan_item_id uuid references public.floor_plan_items(id) on delete set null,
  color text default 'green',
  points jsonb not null default '[]',
  sort_order int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_building_zones_map on public.building_zones(building_map_id);
create index if not exists idx_building_zones_floor on public.building_zones(building_map_id, floor_number);
create index if not exists idx_building_zones_linked_panorama on public.building_zones(linked_panorama_id);
create index if not exists idx_building_zones_linked_fp_item on public.building_zones(linked_floor_plan_item_id);
