CREATE TABLE IF NOT EXISTS public.workspace_share_endpoints (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null unique references public.workspaces(id) on delete cascade,
  endpoint text not null unique,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  CONSTRAINT workspace_share_endpoints_endpoint_format_chk CHECK (endpoint ~ '^[a-z0-9][a-z0-9-]{2,62}$')
);

CREATE INDEX IF NOT EXISTS idx_workspace_share_endpoints_workspace_id ON public.workspace_share_endpoints(workspace_id);
CREATE INDEX IF NOT EXISTS idx_workspace_share_endpoints_endpoint ON public.workspace_share_endpoints(endpoint);
