-- ============================================================
-- Earth Views – migration
-- Globe/map based plot and marker authoring
-- ============================================================

-- 1) Earth Views
create table if not exists public.earth_views (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null default 'Earth View',
  share_token text unique,
  center_lng double precision default 0,
  center_lat double precision default 20,
  zoom double precision default 3,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_earth_views_user on public.earth_views(user_id);
create index if not exists idx_earth_views_org on public.earth_views(org_id);
create index if not exists idx_earth_views_share_token on public.earth_views(share_token);

-- 2) Earth View Plots
create table if not exists public.earth_view_plots (
  id bigint generated by default as identity primary key,
  earth_view_id uuid not null references public.earth_views(id) on delete cascade,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  name text not null,
  area text default '',
  price text default '',
  status text default 'available',
  description text default '',
  color text default 'green',
  media_photo text default '',
  media_video text default '',
  points jsonb not null default '[]',
  sort_order int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_earth_view_plots_view on public.earth_view_plots(earth_view_id);
create index if not exists idx_earth_view_plots_linked_panorama on public.earth_view_plots(linked_panorama_id);
create index if not exists idx_earth_view_plots_status on public.earth_view_plots(status);

-- 3) Earth View Markers
create table if not exists public.earth_view_markers (
  id uuid primary key default gen_random_uuid(),
  earth_view_id uuid not null references public.earth_views(id) on delete cascade,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  name text not null,
  description text default '',
  marker_color text default '#4ade80',
  image_filename text default null,
  voiceover_filename text default null,
  media_photo text default '',
  media_video text default '',
  longitude double precision not null,
  latitude double precision not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_earth_view_markers_view on public.earth_view_markers(earth_view_id);
create index if not exists idx_earth_view_markers_linked_panorama on public.earth_view_markers(linked_panorama_id);
