-- Migration: Add Clients and Client Members tables
-- Run this in Supabase Plotted Development → SQL Editor → New query

-- 1) User Invites (formalizes existing usage)
create table if not exists public.user_invites (
  id               uuid primary key default gen_random_uuid(),
  org_id           uuid not null references public.organizations(id) on delete cascade,
  invited_by       uuid references auth.users(id) on delete set null,
  invited_user_id  uuid references auth.users(id) on delete cascade,
  email            text not null,
  display_name     text,
  role             text not null default 'user',
  status           text not null default 'pending' check (status in ('pending', 'accepted', 'expired')),
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);
create index if not exists idx_user_invites_org_id on public.user_invites(org_id);
create index if not exists idx_user_invites_email on public.user_invites(email);

-- 2) Clients (named client groups)
create table if not exists public.clients (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations(id) on delete cascade,
  name         text not null,
  description  text not null default '',
  members_allowed integer not null default 10 check (members_allowed >= 1),
  created_by   uuid references auth.users(id) on delete set null,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now(),
  unique(org_id, name)
);
create index if not exists idx_clients_org_id on public.clients(org_id);
create index if not exists idx_clients_created_at on public.clients(created_at desc);

-- 3) Client Members (user → client group with role)
create table if not exists public.client_members (
  id           bigint generated by default as identity primary key,
  client_id    uuid not null references public.clients(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  member_role  text not null default 'client_user'
               check (member_role in ('client_admin', 'client_user', 'broker')),
  invited_by   uuid references auth.users(id) on delete set null,
  created_at   timestamptz default now(),
  unique(client_id, user_id)
);
create index if not exists idx_client_members_client_id on public.client_members(client_id);
create index if not exists idx_client_members_user_id on public.client_members(user_id);
create index if not exists idx_client_members_role on public.client_members(member_role);

-- 4) Add client_member_id to access tables (enables cascade cleanup on member removal)
alter table public.workspace_access
  add column if not exists client_member_id bigint
    references public.client_members(id) on delete cascade;

alter table public.panorama_access
  add column if not exists client_member_id bigint
    references public.client_members(id) on delete cascade;
