-- ============================================================
-- PropMark - Full database DDL (Supabase/Postgres)
-- ============================================================
-- Run in Supabase Dashboard → SQL Editor → New query
-- Single file: all tables, indexes, trigger. No ALTERs.

-- 0) Organizations (multi-tenant)
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  accent_color text not null default '#c9a962',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_organizations_created_at on public.organizations(created_at desc);

-- 1) Profiles: app users with role (superadmin | admin | user)
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  role text not null default 'user' check (role in ('superadmin', 'admin', 'user')),
  display_name text,
  email text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_profiles_user_id on public.profiles(user_id);
create index if not exists idx_profiles_org_id on public.profiles(org_id);

-- 2) Workspaces (folders) to organize panoramas + share as a bundle
create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null,
  main_panorama_id bigint,  -- references panoramas(id); FK omitted to avoid circular dependency
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, name)
);

create index if not exists idx_workspaces_user_id on public.workspaces(user_id);
create index if not exists idx_workspaces_org_id on public.workspaces(org_id);
create index if not exists idx_workspaces_updated_at on public.workspaces(updated_at desc);
create index if not exists idx_workspaces_main_panorama_id on public.workspaces(main_panorama_id);

create table if not exists public.workspace_access (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_type text not null check (access_type in ('client', 'viewer')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  unique(workspace_id, user_id)
);

create index if not exists idx_workspace_access_workspace_id on public.workspace_access(workspace_id);
create index if not exists idx_workspace_access_user_id on public.workspace_access(user_id);

create table if not exists public.workspace_share_endpoints (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null unique references public.workspaces(id) on delete cascade,
  endpoint text not null unique check (endpoint ~ '^[a-z0-9][a-z0-9-]{2,62}$'),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_workspace_share_endpoints_workspace_id on public.workspace_share_endpoints(workspace_id);
create index if not exists idx_workspace_share_endpoints_endpoint on public.workspace_share_endpoints(endpoint);

-- 3) Panoramas (owner = user_id)
create table if not exists public.panoramas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  name text not null,
  filename text not null,
  original_filename text not null,
  width int default 0,
  height int default 0,
  is_360 boolean default false,
  use_animated_icons boolean default false,
  start_view jsonb default null,
  image_data text default null,
  image_content_type text default 'image/jpeg',
  audio_filename text default null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_panoramas_user_id on public.panoramas(user_id);
create index if not exists idx_panoramas_org_id on public.panoramas(org_id);
create index if not exists idx_panoramas_workspace_id on public.panoramas(workspace_id);
create index if not exists idx_panoramas_updated_at on public.panoramas(updated_at desc);

-- 3b) Mobile panoramas (linked 1:1 to base panorama)
create table if not exists public.mobile_panoramas (
  id bigint generated by default as identity (start with 1000000000) primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  panorama_parent_id bigint not null references public.panoramas(id) on delete cascade,
  name text not null,
  filename text not null,
  original_filename text not null,
  width int default 0,
  height int default 0,
  is_360 boolean default false,
  use_animated_icons boolean default false,
  start_view jsonb default null,
  image_data text default null,
  image_content_type text default 'image/jpeg',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (panorama_parent_id)
);

create index if not exists idx_mobile_panoramas_user_id on public.mobile_panoramas(user_id);
create index if not exists idx_mobile_panoramas_org_id on public.mobile_panoramas(org_id);
create index if not exists idx_mobile_panoramas_workspace_id on public.mobile_panoramas(workspace_id);
create index if not exists idx_mobile_panoramas_parent_id on public.mobile_panoramas(panorama_parent_id);

-- 4) Plots
create table if not exists public.plots (
  id bigint generated by default as identity primary key,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  name text not null,
  area text default '',
  price text default '',
  status text default 'available',
  description text default '',
  color text default 'emerald',
  media_photo text default '',
  media_video text default '',
  image_data text default null,
  image_filename text default null,
  image_content_type text default 'image/jpeg',
  label_longitude double precision,
  label_latitude double precision,
  points jsonb not null default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_plots_panorama_id on public.plots(panorama_id);
create index if not exists idx_plots_linked_panorama_id on public.plots(linked_panorama_id);

-- 5) 360 marker points (stored as HTML markers metadata)
create table if not exists public.plot_markers (
  id uuid primary key default gen_random_uuid(),
  plot_id text not null,
  name text not null,
  description text default '',
  status text default 'available' check (status in ('available', 'reserved', 'on_hold', 'sold')),
  marker_style text default 'glass',
  marker_icon text default 'mdi:map-marker-radius',
  marker_color text default '#4ade80',
  image_base64 text default null,
  image_filename text default null,
  voiceover_filename text,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  longitude double precision not null,
  latitude double precision not null,
  rotation_x double precision default 0,
  rotation_y double precision default 0,
  rotation_z double precision default 0,
  created_at timestamptz default now()
);

create index if not exists idx_plot_markers_plot_id on public.plot_markers(plot_id);
create index if not exists idx_plot_markers_created_at on public.plot_markers(created_at desc);
create index if not exists idx_plot_markers_linked_panorama_id on public.plot_markers(linked_panorama_id);

-- 6) Panorama access: admin/owner grants client or viewer access to a user
create table if not exists public.panorama_access (
  id bigint generated by default as identity primary key,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_type text not null check (access_type in ('client', 'viewer')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  unique(panorama_id, user_id)
);

create index if not exists idx_panorama_access_panorama_id on public.panorama_access(panorama_id);
create index if not exists idx_panorama_access_user_id on public.panorama_access(user_id);

-- 7) Plot lock access and locks
create table if not exists public.plot_lock_access (
  id uuid primary key default gen_random_uuid(),
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  user_id uuid not null,
  granted_by uuid not null,
  org_id uuid,
  created_at timestamptz default now(),
  unique(panorama_id, user_id)
);

create index if not exists idx_plot_lock_access_panorama on public.plot_lock_access(panorama_id);
create index if not exists idx_plot_lock_access_user on public.plot_lock_access(user_id);

create table if not exists public.plot_locks (
  id uuid primary key default gen_random_uuid(),
  plot_id bigint not null references public.plots(id) on delete cascade,
  locked_by uuid not null,
  locked_for_name text,
  locked_for_email text,
  locked_at timestamptz default now(),
  unique(plot_id)
);

create index if not exists idx_plot_locks_plot on public.plot_locks(plot_id);
create index if not exists idx_plot_locks_locked_by on public.plot_locks(locked_by);

-- 8) Buy interests (captured from customer plot cart checkout; managed in CRM)
create table if not exists public.buy_interests (
  id uuid primary key default gen_random_uuid(),
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  submitted_by uuid references auth.users(id) on delete set null,
  contact_id uuid,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  category text not null default '',
  plots jsonb not null default '[]',
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'won', 'lost')),
  is_contacted boolean not null default false,
  contacted_at timestamptz,
  notes text not null default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_buy_interests_panorama_id on public.buy_interests(panorama_id);
create index if not exists idx_buy_interests_created_at on public.buy_interests(created_at desc);
create index if not exists idx_buy_interests_status on public.buy_interests(status);
create index if not exists idx_buy_interests_contact_id on public.buy_interests(contact_id);

-- 8b) CRM contacts
create table if not exists public.crm_contacts (
  id uuid primary key default gen_random_uuid(),
  org_id uuid references public.organizations(id) on delete set null,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  phone text not null default '',
  email_norm text not null default '',
  phone_norm text not null default '',
  source_interest_id uuid references public.buy_interests(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  notes text not null default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_crm_contacts_org on public.crm_contacts(org_id);
create index if not exists idx_crm_contacts_panorama on public.crm_contacts(panorama_id);
create index if not exists idx_crm_contacts_email_norm on public.crm_contacts(email_norm);
create index if not exists idx_crm_contacts_phone_norm on public.crm_contacts(phone_norm);
create index if not exists idx_crm_contacts_updated on public.crm_contacts(updated_at desc);

-- 8c) CRM deals
create table if not exists public.crm_deals (
  id uuid primary key default gen_random_uuid(),
  org_id uuid references public.organizations(id) on delete set null,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  interest_id uuid references public.buy_interests(id) on delete set null,
  contact_id uuid references public.crm_contacts(id) on delete set null,
  title text not null default '',
  stage text not null default 'new'
    check (stage in ('new', 'contacted', 'site_visit', 'negotiation', 'won', 'lost')),
  is_active boolean not null default true,
  amount text not null default '',
  currency text not null default 'INR',
  plots jsonb not null default '[]',
  project_name text not null default '',
  notes text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_crm_deals_org on public.crm_deals(org_id);
create index if not exists idx_crm_deals_panorama on public.crm_deals(panorama_id);
create index if not exists idx_crm_deals_contact on public.crm_deals(contact_id);
create index if not exists idx_crm_deals_interest on public.crm_deals(interest_id);
create index if not exists idx_crm_deals_stage on public.crm_deals(stage);
create index if not exists idx_crm_deals_updated on public.crm_deals(updated_at desc);
create unique index if not exists uq_crm_deals_interest_active
  on public.crm_deals(interest_id)
  where interest_id is not null and is_active = true;

-- 8d) CRM deal quotes
create table if not exists public.crm_deal_quotes (
  id uuid primary key default gen_random_uuid(),
  deal_id uuid not null references public.crm_deals(id) on delete cascade,
  contact_id uuid references public.crm_contacts(id) on delete set null,
  quote_payload jsonb not null default '{}',
  share_token text not null unique,
  sent_to_email text not null default '',
  sent_to_phone text not null default '',
  shared_via text not null default ''
    check (shared_via in ('', 'email', 'link')),
  sent_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_crm_deal_quotes_deal on public.crm_deal_quotes(deal_id);
create index if not exists idx_crm_deal_quotes_contact on public.crm_deal_quotes(contact_id);
create index if not exists idx_crm_deal_quotes_created on public.crm_deal_quotes(created_at desc);

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'buy_interests'
      and constraint_name = 'buy_interests_contact_id_fkey'
  ) then
    alter table public.buy_interests
      add constraint buy_interests_contact_id_fkey
      foreign key (contact_id) references public.crm_contacts(id) on delete set null;
  end if;
end $$;

-- 9) Trigger: create profile with role 'user' when a new auth user is created
create or replace function public.handle_new_user()
returns trigger as $$
declare
  dn text;
begin
  dn := nullif(trim(coalesce(new.raw_user_meta_data->>'display_name', '')), '');
  insert into public.profiles (user_id, role, display_name, email)
  values (new.id, 'user', dn, new.email)
  on conflict (user_id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 10) Day Night Projects (admin-created day/night panoramic experiences)
create table if not exists public.daynight_projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  name text not null,
  media_type text not null check (media_type in ('image', 'video')),
  stitched_filename text,
  stitched_width int default 0,
  stitched_height int default 0,
  video_filename text,
  video_duration real default 0,
  join_positions jsonb default '[]',
  source_images jsonb default '[]',
  drag_speed real default 80,
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_daynight_projects_user_id on public.daynight_projects(user_id);
create index if not exists idx_daynight_projects_org_id on public.daynight_projects(org_id);
create index if not exists idx_daynight_projects_workspace_id on public.daynight_projects(workspace_id);
create index if not exists idx_daynight_projects_share_token on public.daynight_projects(share_token);

-- 11) Floor Plan Catalogues
create table if not exists public.floor_plan_catalogues (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null default 'Floor Plans',
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_floor_plan_catalogues_user on public.floor_plan_catalogues(user_id);
create index if not exists idx_floor_plan_catalogues_share_token on public.floor_plan_catalogues(share_token);

-- 12) Floor Plan Items (individual images within a catalogue)
create table if not exists public.floor_plan_items (
  id uuid primary key default gen_random_uuid(),
  catalogue_id uuid not null references public.floor_plan_catalogues(id) on delete cascade,
  name text not null,
  image_filename text not null,
  image_width int default 0,
  image_height int default 0,
  file_size_bytes bigint default 0,
  sort_order int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_floor_plan_items_catalogue on public.floor_plan_items(catalogue_id);
create index if not exists idx_floor_plan_items_sort_order on public.floor_plan_items(catalogue_id, sort_order);

-- 13) Building Maps (building panorama/photo containers)
create table if not exists public.building_maps (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  catalogue_id uuid references public.floor_plan_catalogues(id) on delete set null,
  name text not null default 'Building Map',
  image_filename text not null,
  image_width int default 0,
  image_height int default 0,
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_building_maps_user on public.building_maps(user_id);
create index if not exists idx_building_maps_workspace on public.building_maps(workspace_id);
create index if not exists idx_building_maps_catalogue on public.building_maps(catalogue_id);
create index if not exists idx_building_maps_share_token on public.building_maps(share_token);

-- 14) Building Map Images (multiple views per building map)
create table if not exists public.building_map_images (
  id uuid primary key default gen_random_uuid(),
  building_map_id uuid not null references public.building_maps(id) on delete cascade,
  name text not null default 'View',
  image_filename text not null,
  image_width int default 0,
  image_height int default 0,
  sort_order int default 0,
  created_at timestamptz default now()
);

create index if not exists idx_building_map_images_map on public.building_map_images(building_map_id);
create index if not exists idx_building_map_images_sort on public.building_map_images(building_map_id, sort_order);

-- 15) Building Zones (polygon areas drawn on a building map image)
create table if not exists public.building_zones (
  id bigint generated by default as identity primary key,
  building_map_id uuid not null references public.building_maps(id) on delete cascade,
  image_id uuid references public.building_map_images(id) on delete cascade,
  name text not null,
  floor_number int not null default 0 check (floor_number >= 0 and floor_number <= 100),
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  linked_floor_plan_item_id uuid references public.floor_plan_items(id) on delete set null,
  color text default 'green',
  points jsonb not null default '[]',
  sort_order int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_building_zones_map on public.building_zones(building_map_id);
create index if not exists idx_building_zones_image on public.building_zones(image_id);
create index if not exists idx_building_zones_floor on public.building_zones(building_map_id, floor_number);
create index if not exists idx_building_zones_linked_panorama on public.building_zones(linked_panorama_id);
create index if not exists idx_building_zones_linked_fp_item on public.building_zones(linked_floor_plan_item_id);

-- 16) Project Plans (bundles multiple building maps into a single shareable view)
create table if not exists public.project_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  name text not null default 'Project Plan',
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_project_plans_user on public.project_plans(user_id);
create index if not exists idx_project_plans_workspace on public.project_plans(workspace_id);
create index if not exists idx_project_plans_share_token on public.project_plans(share_token);

-- 17) Project Plan Maps (many-to-many link between project plans and building maps)
create table if not exists public.project_plan_maps (
  id bigint generated by default as identity primary key,
  project_plan_id uuid not null references public.project_plans(id) on delete cascade,
  building_map_id uuid not null references public.building_maps(id) on delete cascade,
  sort_order int not null default 0,
  created_at timestamptz default now(),
  unique(project_plan_id, building_map_id)
);

create index if not exists idx_project_plan_maps_plan on public.project_plan_maps(project_plan_id);
create index if not exists idx_project_plan_maps_building on public.project_plan_maps(building_map_id);

-- 18) Galleries
create table if not exists public.galleries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  name text not null default 'Gallery',
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_galleries_user on public.galleries(user_id);
create index if not exists idx_galleries_workspace on public.galleries(workspace_id);
create index if not exists idx_galleries_share_token on public.galleries(share_token);

-- 19) Gallery Items (images or videos within a gallery)
create table if not exists public.gallery_items (
  id uuid primary key default gen_random_uuid(),
  gallery_id uuid not null references public.galleries(id) on delete cascade,
  name text not null,
  media_type text not null default 'image',
  filename text not null,
  file_size_bytes bigint default 0,
  media_width int default 0,
  media_height int default 0,
  sort_order int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_gallery_items_gallery on public.gallery_items(gallery_id);
create index if not exists idx_gallery_items_sort_order on public.gallery_items(gallery_id, sort_order);

-- 20) Earth Views
create table if not exists public.earth_views (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null default 'Earth View',
  share_token text unique,
  center_lng double precision default 0,
  center_lat double precision default 20,
  zoom double precision default 3,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_earth_views_user on public.earth_views(user_id);
create index if not exists idx_earth_views_org on public.earth_views(org_id);
create index if not exists idx_earth_views_share_token on public.earth_views(share_token);

-- 21) Earth View Plots
create table if not exists public.earth_view_plots (
  id bigint generated by default as identity primary key,
  earth_view_id uuid not null references public.earth_views(id) on delete cascade,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  name text not null,
  area text default '',
  price text default '',
  status text default 'available',
  description text default '',
  color text default 'green',
  media_photo text default '',
  media_video text default '',
  points jsonb not null default '[]',
  sort_order int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_earth_view_plots_view on public.earth_view_plots(earth_view_id);
create index if not exists idx_earth_view_plots_linked_panorama on public.earth_view_plots(linked_panorama_id);
create index if not exists idx_earth_view_plots_status on public.earth_view_plots(status);

-- 22) Earth View Markers
create table if not exists public.earth_view_markers (
  id uuid primary key default gen_random_uuid(),
  earth_view_id uuid not null references public.earth_views(id) on delete cascade,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  name text not null,
  description text default '',
  marker_color text default '#4ade80',
  image_filename text default null,
  voiceover_filename text default null,
  media_photo text default '',
  media_video text default '',
  longitude double precision not null,
  latitude double precision not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_earth_view_markers_view on public.earth_view_markers(earth_view_id);
create index if not exists idx_earth_view_markers_linked_panorama on public.earth_view_markers(linked_panorama_id);

-- 23) User Invites (formalizes existing usage in invite flow)
create table if not exists public.user_invites (
  id               uuid primary key default gen_random_uuid(),
  org_id           uuid not null references public.organizations(id) on delete cascade,
  invited_by       uuid references auth.users(id) on delete set null,
  invited_user_id  uuid references auth.users(id) on delete cascade,
  email            text not null,
  display_name     text,
  role             text not null default 'user',
  status           text not null default 'pending' check (status in ('pending', 'accepted', 'expired')),
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

create index if not exists idx_user_invites_org_id on public.user_invites(org_id);
create index if not exists idx_user_invites_email on public.user_invites(email);

-- 24) Clients (named client groups within an org, managed by admin)
create table if not exists public.clients (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations(id) on delete cascade,
  name         text not null,
  description  text not null default '',
  created_by   uuid references auth.users(id) on delete set null,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now(),
  unique(org_id, name)
);

create index if not exists idx_clients_org_id on public.clients(org_id);
create index if not exists idx_clients_created_at on public.clients(created_at desc);

-- 25) Client Members (users assigned to a client group with a role)
create table if not exists public.client_members (
  id           bigint generated by default as identity primary key,
  client_id    uuid not null references public.clients(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  member_role  text not null default 'client_user'
               check (member_role in ('client_admin', 'client_user', 'broker')),
  invited_by   uuid references auth.users(id) on delete set null,
  created_at   timestamptz default now(),
  unique(client_id, user_id)
);

create index if not exists idx_client_members_client_id on public.client_members(client_id);
create index if not exists idx_client_members_user_id on public.client_members(user_id);
create index if not exists idx_client_members_role on public.client_members(member_role);

-- 26) Add client_member_id to access tables for cascade cleanup on member removal
alter table public.workspace_access
  add column if not exists client_member_id bigint
    references public.client_members(id) on delete cascade;

alter table public.panorama_access
  add column if not exists client_member_id bigint
    references public.client_members(id) on delete cascade;

-- 27) Client Team Invites (email/share-link based join flow)
create table if not exists public.client_team_invites (
  id                uuid primary key default gen_random_uuid(),
  client_id         uuid not null references public.clients(id) on delete cascade,
  org_id            uuid not null references public.organizations(id) on delete cascade,
  invited_by        uuid references auth.users(id) on delete set null,
  email             text not null,
  display_name      text not null default '',
  member_role       text not null default 'client_user'
                    check (member_role in ('client_user', 'broker')),
  invite_token      text not null unique,
  invite_link       text,
  status            text not null default 'pending'
                    check (status in ('pending', 'accepted', 'expired', 'cancelled')),
  expires_at        timestamptz,
  accepted_at       timestamptz,
  accepted_user_id  uuid references auth.users(id) on delete set null,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create index if not exists idx_client_team_invites_client_id on public.client_team_invites(client_id);
create index if not exists idx_client_team_invites_org_id on public.client_team_invites(org_id);
create index if not exists idx_client_team_invites_email on public.client_team_invites(email);
create index if not exists idx_client_team_invites_status on public.client_team_invites(status);
create index if not exists idx_client_team_invites_token on public.client_team_invites(invite_token);
