-- ============================================================
-- PropMark - Full database DDL (Supabase/Postgres)
-- ============================================================
-- Run in Supabase Dashboard → SQL Editor → New query
-- Single file: all tables, indexes, trigger. No ALTERs.

-- 0) Organizations (multi-tenant)
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  accent_color text not null default '#c9a962',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_organizations_created_at on public.organizations(created_at desc);

-- 1) Profiles: app users with role (superadmin | admin | user)
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  role text not null default 'user' check (role in ('superadmin', 'admin', 'user')),
  display_name text,
  email text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_profiles_user_id on public.profiles(user_id);
create index if not exists idx_profiles_org_id on public.profiles(org_id);

-- 2) Workspaces (folders) to organize panoramas + share as a bundle
create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null,
  main_panorama_id bigint,  -- references panoramas(id); FK omitted to avoid circular dependency
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, name)
);

create index if not exists idx_workspaces_user_id on public.workspaces(user_id);
create index if not exists idx_workspaces_org_id on public.workspaces(org_id);
create index if not exists idx_workspaces_updated_at on public.workspaces(updated_at desc);
create index if not exists idx_workspaces_main_panorama_id on public.workspaces(main_panorama_id);

create table if not exists public.workspace_access (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_type text not null check (access_type in ('client', 'viewer')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  unique(workspace_id, user_id)
);

create index if not exists idx_workspace_access_workspace_id on public.workspace_access(workspace_id);
create index if not exists idx_workspace_access_user_id on public.workspace_access(user_id);

create table if not exists public.workspace_share_endpoints (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null unique references public.workspaces(id) on delete cascade,
  endpoint text not null unique check (endpoint ~ '^[a-z0-9][a-z0-9-]{2,62}$'),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_workspace_share_endpoints_workspace_id on public.workspace_share_endpoints(workspace_id);
create index if not exists idx_workspace_share_endpoints_endpoint on public.workspace_share_endpoints(endpoint);

-- 3) Panoramas (owner = user_id)
create table if not exists public.panoramas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  name text not null,
  filename text not null,
  original_filename text not null,
  width int default 0,
  height int default 0,
  is_360 boolean default false,
  use_animated_icons boolean default false,
  start_view jsonb default null,
  image_data text default null,
  image_content_type text default 'image/jpeg',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_panoramas_user_id on public.panoramas(user_id);
create index if not exists idx_panoramas_org_id on public.panoramas(org_id);
create index if not exists idx_panoramas_workspace_id on public.panoramas(workspace_id);
create index if not exists idx_panoramas_updated_at on public.panoramas(updated_at desc);

-- 4) Plots
create table if not exists public.plots (
  id bigint generated by default as identity primary key,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  name text not null,
  area text default '',
  price text default '',
  status text default 'available',
  description text default '',
  color text default 'emerald',
  media_photo text default '',
  media_video text default '',
  image_data text default null,
  image_filename text default null,
  image_content_type text default 'image/jpeg',
  label_longitude double precision,
  label_latitude double precision,
  points jsonb not null default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_plots_panorama_id on public.plots(panorama_id);
create index if not exists idx_plots_linked_panorama_id on public.plots(linked_panorama_id);

-- 5) 360 marker points (stored as HTML markers metadata)
create table if not exists public.plot_markers (
  id uuid primary key default gen_random_uuid(),
  plot_id text not null,
  name text not null,
  description text default '',
  status text default 'available' check (status in ('available', 'reserved', 'on_hold', 'sold')),
  marker_style text default 'glass',
  marker_icon text default 'mdi:map-marker-radius',
  marker_color text default '#4ade80',
  image_base64 text default null,
  image_filename text default null,
  voiceover_filename text,
  linked_panorama_id bigint references public.panoramas(id) on delete set null,
  longitude double precision not null,
  latitude double precision not null,
  rotation_x double precision default 0,
  rotation_y double precision default 0,
  rotation_z double precision default 0,
  created_at timestamptz default now()
);

create index if not exists idx_plot_markers_plot_id on public.plot_markers(plot_id);
create index if not exists idx_plot_markers_created_at on public.plot_markers(created_at desc);
create index if not exists idx_plot_markers_linked_panorama_id on public.plot_markers(linked_panorama_id);

-- 6) Panorama access: admin/owner grants client or viewer access to a user
create table if not exists public.panorama_access (
  id bigint generated by default as identity primary key,
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_type text not null check (access_type in ('client', 'viewer')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  unique(panorama_id, user_id)
);

create index if not exists idx_panorama_access_panorama_id on public.panorama_access(panorama_id);
create index if not exists idx_panorama_access_user_id on public.panorama_access(user_id);

-- 7) Plot lock access and locks
create table if not exists public.plot_lock_access (
  id uuid primary key default gen_random_uuid(),
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  user_id uuid not null,
  granted_by uuid not null,
  org_id uuid,
  created_at timestamptz default now(),
  unique(panorama_id, user_id)
);

create index if not exists idx_plot_lock_access_panorama on public.plot_lock_access(panorama_id);
create index if not exists idx_plot_lock_access_user on public.plot_lock_access(user_id);

create table if not exists public.plot_locks (
  id uuid primary key default gen_random_uuid(),
  plot_id bigint not null references public.plots(id) on delete cascade,
  locked_by uuid not null,
  locked_for_name text,
  locked_for_email text,
  locked_at timestamptz default now(),
  unique(plot_id)
);

create index if not exists idx_plot_locks_plot on public.plot_locks(plot_id);
create index if not exists idx_plot_locks_locked_by on public.plot_locks(locked_by);

-- 8) Buy interests (captured from customer plot cart checkout; managed in CRM)
create table if not exists public.buy_interests (
  id uuid primary key default gen_random_uuid(),
  panorama_id bigint not null references public.panoramas(id) on delete cascade,
  submitted_by uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  category text not null default '',
  plots jsonb not null default '[]',
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'won', 'lost')),
  notes text not null default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_buy_interests_panorama_id on public.buy_interests(panorama_id);
create index if not exists idx_buy_interests_created_at on public.buy_interests(created_at desc);
create index if not exists idx_buy_interests_status on public.buy_interests(status);

-- 9) Trigger: create profile with role 'user' when a new auth user is created
create or replace function public.handle_new_user()
returns trigger as $$
declare
  dn text;
begin
  dn := nullif(trim(coalesce(new.raw_user_meta_data->>'display_name', '')), '');
  insert into public.profiles (user_id, role, display_name, email)
  values (new.id, 'user', dn, new.email)
  on conflict (user_id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 10) Day Night Projects (admin-created day/night panoramic experiences)
create table if not exists public.daynight_projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid references public.organizations(id) on delete set null,
  name text not null,
  media_type text not null check (media_type in ('image', 'video')),
  stitched_filename text,
  stitched_width int default 0,
  stitched_height int default 0,
  video_filename text,
  video_duration real default 0,
  join_positions jsonb default '[]',
  source_images jsonb default '[]',
  drag_speed real default 80,
  share_token text unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_daynight_projects_user_id on public.daynight_projects(user_id);
create index if not exists idx_daynight_projects_org_id on public.daynight_projects(org_id);
create index if not exists idx_daynight_projects_share_token on public.daynight_projects(share_token);
